import '../models/meal.dart';
import '../models/exercise.dart';
import 'session_manager.dart';
import 'backend_service.dart';
import 'package:flutter/material.dart';

class NutritionExerciseService {
  static final NutritionExerciseService _instance = NutritionExerciseService._internal();
  factory NutritionExerciseService() => _instance;
  NutritionExerciseService._internal();

  final BackendService _backendService = BackendService();

  // Default meals organized by pregnancy-specific nutritional categories
  List<Meal> _getDefaultMeals() {
    return [
      // 1. Balanced Nutrition
      Meal(
        id: 'balanced_1',
        name: 'Quinoa',
        description: 'Complete protein with all essential amino acids',
        imageUrl: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80',
        category: 'Balanced Nutrition',
        nutritionalBenefits: ['Complete Protein', 'Fiber', 'Iron', 'Magnesium'],
        calories: 222,
        isPregnancySafe: true,
        preparation: 'Rinse quinoa, cook in water or broth for 15 minutes',
        ingredients: ['Quinoa', 'Water or broth'],
      ),
      Meal(
        id: 'balanced_2',
        name: 'Lean Chicken Breast',
        description: 'High-quality protein for maternal and fetal development',
        imageUrl: 'https://images.unsplash.com/photo-1604503468506-a8da13d82791?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80',
        category: 'Balanced Nutrition',
        nutritionalBenefits: ['High Protein', 'B Vitamins', 'Phosphorus', 'Selenium'],
        calories: 165,
        isPregnancySafe: true,
        preparation: 'Cook thoroughly to internal temperature of 165°F',
        ingredients: ['Chicken breast', 'Herbs', 'Olive oil'],
      ),
      Meal(
        id: 'balanced_3',
        name: 'Avocado',
        description: 'Rich in folate and healthy monounsaturated fats',
        imageUrl: 'https://images.unsplash.com/photo-1523049673857-eb18f1d7b578?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80',
        category: 'Balanced Nutrition',
        nutritionalBenefits: ['Folate', 'Healthy Fats', 'Fiber', 'Potassium'],
        calories: 234,
        isPregnancySafe: true,
        preparation: 'Slice and add to meals or make guacamole',
        ingredients: ['Ripe avocado', 'Lime juice', 'Salt'],
      ),
      Meal(
        id: 'balanced_4',
        name: 'Sweet Potatoes',
        description: 'Beta-carotene for vitamin A and complex carbohydrates',
        imageUrl: 'https://images.unsplash.com/photo-1518977676601-b53f82aba655?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80',
        category: 'Balanced Nutrition',
        nutritionalBenefits: ['Beta-carotene', 'Vitamin A', 'Fiber', 'Potassium'],
        calories: 112,
        isPregnancySafe: true,
        preparation: 'Bake at 400°F for 45 minutes or steam until tender',
        ingredients: ['Sweet potato', 'Olive oil', 'Herbs'],
      ),
      Meal(
        id: 'balanced_5',
        name: 'Mixed Berries',
        description: 'Antioxidants and vitamin C for immune support',
        imageUrl: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80',
        category: 'Balanced Nutrition',
        nutritionalBenefits: ['Antioxidants', 'Vitamin C', 'Fiber', 'Folate'],
        calories: 85,
        isPregnancySafe: true,
        preparation: 'Wash thoroughly and enjoy fresh or in smoothies',
        ingredients: ['Strawberries', 'Blueberries', 'Raspberries'],
      ),
      Meal(
        id: 'balanced_6',
        name: 'Brown Rice',
        description: 'Whole grain providing sustained energy and B vitamins',
        imageUrl: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80',
        category: 'Balanced Nutrition',
        nutritionalBenefits: ['Complex Carbs', 'B Vitamins', 'Fiber', 'Manganese'],
        calories: 216,
        isPregnancySafe: true,
        preparation: 'Cook in 2:1 water to rice ratio for 45 minutes',
        ingredients: ['Brown rice', 'Water', 'Salt'],
      ),
      Meal(
        id: 'balanced_7',
        name: 'Edamame',
        description: 'Plant-based protein and folate powerhouse',
        imageUrl: 'https://images.unsplash.com/photo-1609501676725-7186f73b2c92?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80',
        category: 'Balanced Nutrition',
        nutritionalBenefits: ['Plant Protein', 'Folate', 'Fiber', 'Isoflavones'],
        calories: 188,
        isPregnancySafe: true,
        preparation: 'Steam or boil for 5 minutes, season with sea salt',
        ingredients: ['Edamame pods', 'Sea salt'],
      ),
      Meal(
        id: 'balanced_8',
        name: 'Bell Peppers',
        description: 'High vitamin C content and colorful antioxidants',
        imageUrl: 'https://images.unsplash.com/photo-1525607551862-4db5ed5ba4a4?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80',
        category: 'Balanced Nutrition',
        nutritionalBenefits: ['Vitamin C', 'Antioxidants', 'Vitamin A', 'Folate'],
        calories: 24,
        isPregnancySafe: true,
        preparation: 'Eat raw, roast, or sauté with olive oil',
        ingredients: ['Bell peppers', 'Olive oil', 'Garlic'],
      ),

      // 2. High Protein
      Meal(
        id: 'protein_1',
        name: 'Plain Greek Yogurt',
        description: 'Double the protein of regular yogurt plus probiotics',
        imageUrl: 'https://images.unsplash.com/photo-1488477181946-6428a0291777?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80',
        category: 'High Protein',
        nutritionalBenefits: ['High Protein', 'Probiotics', 'Calcium', 'B12'],
        calories: 130,
        isPregnancySafe: true,
        preparation: 'Serve with fresh fruits or nuts',
        ingredients: ['Greek yogurt', 'Fresh berries', 'Honey'],
      ),
      Meal(
        id: 'protein_2',
        name: 'Eggs (Cooked)',
        description: 'Complete protein with choline for brain development',
        imageUrl: 'https://images.unsplash.com/photo-1518492104633-130d0cc84637?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80',
        category: 'High Protein',
        nutritionalBenefits: ['Complete Protein', 'Choline', 'Vitamin D', 'B12'],
        calories: 155,
        isPregnancySafe: true,
        preparation: 'Cook thoroughly - scrambled, boiled, or poached',
        ingredients: ['Eggs', 'Milk', 'Butter', 'Salt'],
      ),
      Meal(
        id: 'protein_3',
        name: 'Salmon (Low-mercury choice)',
        description: 'Omega-3 fatty acids and high-quality protein',
        imageUrl: 'https://images.unsplash.com/photo-1467003909585-2f8a72700288?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80',
        category: 'High Protein',
        nutritionalBenefits: ['Omega-3', 'High Protein', 'Vitamin D', 'B Vitamins'],
        calories: 206,
        isPregnancySafe: true,
        preparation: 'Bake at 400°F for 12-15 minutes until flaky',
        ingredients: ['Salmon fillet', 'Lemon', 'Herbs', 'Olive oil'],
      ),
      Meal(
        id: 'protein_4',
        name: 'Chickpeas',
        description: 'Plant-based protein with fiber and folate',
        imageUrl: 'https://images.unsplash.com/photo-1599909533980-d905c27c4a8c?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80',
        category: 'High Protein',
        nutritionalBenefits: ['Plant Protein', 'Fiber', 'Folate', 'Iron'],
        calories: 164,
        isPregnancySafe: true,
        preparation: 'Use canned (rinsed) or cook dried chickpeas',
        ingredients: ['Chickpeas', 'Olive oil', 'Cumin', 'Garlic'],
      ),
      Meal(
        id: 'protein_5',
        name: 'Cottage Cheese',
        description: 'High protein with calcium for bone health',
        imageUrl: 'https://images.unsplash.com/photo-1589881133595-9b9dd96c8fd3?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80',
        category: 'High Protein',
        nutritionalBenefits: ['High Protein', 'Calcium', 'Phosphorus', 'B12'],
        calories: 206,
        isPregnancySafe: true,
        preparation: 'Serve with fresh fruit or vegetables',
        ingredients: ['Cottage cheese', 'Fresh fruit', 'Nuts'],
      ),
      Meal(
        id: 'protein_6',
        name: 'Lentils',
        description: 'Protein-rich legumes with iron and folate',
        imageUrl: 'https://images.unsplash.com/photo-1509358271058-acd22cc93898?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80',
        category: 'High Protein',
        nutritionalBenefits: ['Plant Protein', 'Iron', 'Folate', 'Fiber'],
        calories: 230,
        isPregnancySafe: true,
        preparation: 'Cook in broth for 20-25 minutes until tender',
        ingredients: ['Lentils', 'Vegetable broth', 'Onion', 'Garlic'],
      ),
      Meal(
        id: 'protein_7',
        name: 'Lean Beef (Well-cooked)',
        description: 'Iron-rich protein for preventing anemia',
        imageUrl: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80',
        category: 'High Protein',
        nutritionalBenefits: ['High Protein', 'Iron', 'Zinc', 'B12'],
        calories: 250,
        isPregnancySafe: true,
        preparation: 'Cook to internal temperature of 160°F',
        ingredients: ['Lean beef', 'Onions', 'Herbs', 'Olive oil'],
      ),
      Meal(
        id: 'protein_8',
        name: 'Tofu or Tempeh',
        description: 'Soy-based protein with isoflavones',
        imageUrl: 'https://images.unsplash.com/photo-1609501676725-7186f73b2c92?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80',
        category: 'High Protein',
        nutritionalBenefits: ['Plant Protein', 'Isoflavones', 'Calcium', 'Iron'],
        calories: 181,
        isPregnancySafe: true,
        preparation: 'Marinate and bake, stir-fry, or grill',
        ingredients: ['Tofu/Tempeh', 'Soy sauce', 'Ginger', 'Garlic'],
      ),

      // 3. Low Sodium
      Meal(
        id: 'lowsodium_1',
        name: 'Fresh Vegetables (Carrots, Broccoli)',
        description: 'Nutrient-dense vegetables without added sodium',
        imageUrl: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80',
        category: 'Low Sodium',
        nutritionalBenefits: ['Vitamins', 'Minerals', 'Fiber', 'Antioxidants'],
        calories: 35,
        isPregnancySafe: true,
        preparation: 'Steam, roast, or eat raw with natural seasonings',
        ingredients: ['Fresh vegetables', 'Herbs', 'Lemon juice'],
      ),
      Meal(
        id: 'lowsodium_2',
        name: 'Fresh Fruits (Bananas, Apples)',
        description: 'Natural sweetness and potassium without sodium',
        imageUrl: 'https://images.unsplash.com/photo-1491553895911-0055eca6402d?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80',
        category: 'Low Sodium',
        nutritionalBenefits: ['Potassium', 'Vitamin C', 'Fiber', 'Natural Sugars'],
        calories: 95,
        isPregnancySafe: true,
        preparation: 'Eat fresh, add to smoothies or yogurt',
        ingredients: ['Fresh fruits', 'Cinnamon'],
      ),
      Meal(
        id: 'lowsodium_3',
        name: 'Unsalted Nuts and Seeds',
        description: 'Healthy fats and protein without added salt',
        imageUrl: 'https://images.unsplash.com/photo-1508747747105-8bf65b2ad4e8?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80',
        category: 'Low Sodium',
        nutritionalBenefits: ['Healthy Fats', 'Protein', 'Vitamin E', 'Magnesium'],
        calories: 160,
        isPregnancySafe: true,
        preparation: 'Eat raw or lightly toasted without salt',
        ingredients: ['Mixed nuts', 'Seeds'],
      ),
      Meal(
        id: 'lowsodium_4',
        name: 'Fresh Herbs (Basil, Oregano, Thyme)',
        description: 'Natural flavor enhancers rich in antioxidants',
        imageUrl: 'https://images.unsplash.com/photo-1462536943532-57a629f6cc60?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80',
        category: 'Low Sodium',
        nutritionalBenefits: ['Antioxidants', 'Vitamins', 'Flavor', 'Anti-inflammatory'],
        calories: 1,
        isPregnancySafe: true,
        preparation: 'Add fresh to dishes for natural flavor',
        ingredients: ['Fresh herbs'],
      ),
      Meal(
        id: 'lowsodium_5',
        name: 'Dried Beans and Peas (rinsed)',
        description: 'Protein and fiber with reduced sodium content',
        imageUrl: 'https://images.unsplash.com/photo-1618197188096-2c0671a77c5f?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80',
        category: 'Low Sodium',
        nutritionalBenefits: ['Plant Protein', 'Fiber', 'Folate', 'Iron'],
        calories: 245,
        isPregnancySafe: true,
        preparation: 'Rinse canned beans or cook dried beans from scratch',
        ingredients: ['Beans/peas', 'Water', 'Bay leaves'],
      ),
      Meal(
        id: 'lowsodium_6',
        name: 'Whole Grains (Oats, Quinoa)',
        description: 'Complex carbohydrates without added sodium',
        imageUrl: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80',
        category: 'Low Sodium',
        nutritionalBenefits: ['Complex Carbs', 'Fiber', 'B Vitamins', 'Iron'],
        calories: 150,
        isPregnancySafe: true,
        preparation: 'Cook in water or low-sodium broth',
        ingredients: ['Whole grains', 'Water', 'Cinnamon'],
      ),
      Meal(
        id: 'lowsodium_7',
        name: 'Lean, Unseasoned Meat/Poultry',
        description: 'Pure protein without sodium-heavy seasonings',
        imageUrl: 'https://images.unsplash.com/photo-1608039755401-742074f0548d?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80',
        category: 'Low Sodium',
        nutritionalBenefits: ['High Protein', 'Iron', 'B Vitamins', 'Zinc'],
        calories: 185,
        isPregnancySafe: true,
        preparation: 'Season with herbs and spices, cook thoroughly',
        ingredients: ['Lean meat', 'Fresh herbs', 'Garlic'],
      ),
      Meal(
        id: 'lowsodium_8',
        name: 'Garlic and Onion Powder (No salt added)',
        description: 'Flavor enhancers without sodium content',
        imageUrl: 'https://images.unsplash.com/photo-1533725602584-3d28f8fac30a?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80',
        category: 'Low Sodium',
        nutritionalBenefits: ['Flavor', 'Antioxidants', 'Anti-inflammatory'],
        calories: 10,
        isPregnancySafe: true,
        preparation: 'Use as seasoning in place of salt',
        ingredients: ['Garlic powder', 'Onion powder'],
      ),

      // 4. Diabetic Friendly
      Meal(
        id: 'diabetic_1',
        name: 'Black Beans',
        description: 'Low glycemic index protein with stable blood sugar',
        imageUrl: 'https://images.unsplash.com/photo-1579952363873-27d3bfad9c0d?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80',
        category: 'Diabetic Friendly',
        nutritionalBenefits: ['Low GI', 'Plant Protein', 'Fiber', 'Folate'],
        calories: 227,
        isPregnancySafe: true,
        preparation: 'Cook with bay leaves and cumin for flavor',
        ingredients: ['Black beans', 'Bay leaves', 'Cumin', 'Garlic'],
      ),
      Meal(
        id: 'diabetic_2',
        name: 'Lentils',
        description: 'Slow-releasing energy with blood sugar stability',
        imageUrl: 'https://images.unsplash.com/photo-1509358271058-acd22cc93898?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80',
        category: 'Diabetic Friendly',
        nutritionalBenefits: ['Low GI', 'Plant Protein', 'Iron', 'Folate'],
        calories: 230,
        isPregnancySafe: true,
        preparation: 'Cook in vegetable broth with herbs',
        ingredients: ['Lentils', 'Vegetable broth', 'Thyme', 'Onion'],
      ),
      Meal(
        id: 'diabetic_3',
        name: 'Whole Oats (Steel-cut or Rolled)',
        description: 'Beta-glucan fiber for blood sugar control',
        imageUrl: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80',
        category: 'Diabetic Friendly',
        nutritionalBenefits: ['Beta-glucan', 'Fiber', 'Complex Carbs', 'Protein'],
        calories: 150,
        isPregnancySafe: true,
        preparation: 'Cook slowly with water or milk, add cinnamon',
        ingredients: ['Steel-cut oats', 'Water', 'Cinnamon', 'Berries'],
      ),
      Meal(
        id: 'diabetic_4',
        name: 'Non-starchy Vegetables (Spinach, Zucchini)',
        description: 'Low carb, high nutrient vegetables',
        imageUrl: 'https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80',
        category: 'Diabetic Friendly',
        nutritionalBenefits: ['Low Carb', 'High Nutrients', 'Fiber', 'Antioxidants'],
        calories: 20,
        isPregnancySafe: true,
        preparation: 'Sauté with olive oil and garlic',
        ingredients: ['Leafy greens', 'Zucchini', 'Olive oil', 'Garlic'],
      ),
      Meal(
        id: 'diabetic_5',
        name: 'Avocado',
        description: 'Healthy fats that help stabilize blood sugar',
        imageUrl: 'https://images.unsplash.com/photo-1523049673857-eb18f1d7b578?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80',
        category: 'Diabetic Friendly',
        nutritionalBenefits: ['Healthy Fats', 'Fiber', 'Low GI', 'Folate'],
        calories: 234,
        isPregnancySafe: true,
        preparation: 'Add to salads or eat with whole grain toast',
        ingredients: ['Avocado', 'Lime', 'Sea salt'],
      ),
      Meal(
        id: 'diabetic_6',
        name: 'Berries (Strawberries, Blueberries)',
        description: 'Lower sugar fruits with antioxidants',
        imageUrl: 'https://images.unsplash.com/photo-1498557850523-fd3d118b962e?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80',
        category: 'Diabetic Friendly',
        nutritionalBenefits: ['Antioxidants', 'Lower Sugar', 'Fiber', 'Vitamin C'],
        calories: 85,
        isPregnancySafe: true,
        preparation: 'Eat fresh or add to yogurt',
        ingredients: ['Mixed berries'],
      ),
      Meal(
        id: 'diabetic_7',
        name: 'Nuts (Almonds, Walnuts)',
        description: 'Healthy fats and protein for blood sugar stability',
        imageUrl: 'https://images.unsplash.com/photo-1508747747105-8bf65b2ad4e8?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80',
        category: 'Diabetic Friendly',
        nutritionalBenefits: ['Healthy Fats', 'Protein', 'Low Carb', 'Vitamin E'],
        calories: 160,
        isPregnancySafe: true,
        preparation: 'Eat raw or lightly toasted, portion controlled',
        ingredients: ['Mixed nuts'],
      ),
      Meal(
        id: 'diabetic_8',
        name: 'Whole Grain Bread (100% whole wheat)',
        description: 'Complex carbohydrates with slower glucose response',
        imageUrl: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80',
        category: 'Diabetic Friendly',
        nutritionalBenefits: ['Complex Carbs', 'Fiber', 'B Vitamins', 'Iron'],
        calories: 80,
        isPregnancySafe: true,
        preparation: 'Toast lightly, pair with protein',
        ingredients: ['100% whole wheat bread', 'Avocado', 'Tomato'],
      ),

      // 5. High Fiber
      Meal(
        id: 'fiber_1',
        name: 'Raspberries',
        description: 'Highest fiber content among common fruits',
        imageUrl: 'https://images.unsplash.com/photo-1564885879020-34ac9e094d55?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80',
        category: 'High Fiber',
        nutritionalBenefits: ['High Fiber', 'Vitamin C', 'Antioxidants', 'Manganese'],
        calories: 65,
        isPregnancySafe: true,
        preparation: 'Eat fresh or add to yogurt and oatmeal',
        ingredients: ['Fresh raspberries'],
      ),
      Meal(
        id: 'fiber_2',
        name: 'Blackberries',
        description: 'Fiber-rich berries for digestive health',
        imageUrl: 'https://images.unsplash.com/photo-1502945015378-0e284ca1a5be?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80',
        category: 'High Fiber',
        nutritionalBenefits: ['High Fiber', 'Vitamin C', 'Vitamin K', 'Antioxidants'],
        calories: 62,
        isPregnancySafe: true,
        preparation: 'Enjoy fresh or blend into smoothies',
        ingredients: ['Fresh blackberries'],
      ),
      Meal(
        id: 'fiber_3',
        name: 'Chia Seeds',
        description: 'Soluble fiber that helps with constipation',
        imageUrl: 'https://images.unsplash.com/photo-1553909489-cd47e0ef937f?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80',
        category: 'High Fiber',
        nutritionalBenefits: ['Soluble Fiber', 'Omega-3', 'Protein', 'Calcium'],
        calories: 138,
        isPregnancySafe: true,
        preparation: 'Soak in liquid to form gel, add to foods',
        ingredients: ['Chia seeds', 'Almond milk', 'Vanilla'],
      ),
      Meal(
        id: 'fiber_4',
        name: 'Flaxseeds',
        description: 'Ground flaxseeds provide fiber and omega-3s',
        imageUrl: 'https://images.unsplash.com/photo-1601648764658-cf37e8c1d75d?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80',
        category: 'High Fiber',
        nutritionalBenefits: ['High Fiber', 'Omega-3', 'Lignans', 'Protein'],
        calories: 150,
        isPregnancySafe: true,
        preparation: 'Use ground flaxseeds, add to smoothies or yogurt',
        ingredients: ['Ground flaxseeds'],
      ),
      Meal(
        id: 'fiber_5',
        name: 'Pears (with skin)',
        description: 'High fiber fruit that aids digestion',
        imageUrl: 'https://images.unsplash.com/photo-1615438405282-89eb64647adf?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80',
        category: 'High Fiber',
        nutritionalBenefits: ['High Fiber', 'Vitamin C', 'Potassium', 'Antioxidants'],
        calories: 102,
        isPregnancySafe: true,
        preparation: 'Eat with skin on for maximum fiber',
        ingredients: ['Fresh pears'],
      ),
      Meal(
        id: 'fiber_6',
        name: 'Kidney Beans',
        description: 'Legumes high in both soluble and insoluble fiber',
        imageUrl: 'https://images.unsplash.com/photo-1585301515064-3d8c6b8418d8?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80',
        category: 'High Fiber',
        nutritionalBenefits: ['High Fiber', 'Plant Protein', 'Iron', 'Folate'],
        calories: 225,
        isPregnancySafe: true,
        preparation: 'Use canned (rinsed) or cook dried beans',
        ingredients: ['Kidney beans', 'Tomatoes', 'Onion', 'Herbs'],
      ),
      Meal(
        id: 'fiber_7',
        name: 'Artichokes',
        description: 'Vegetable with one of the highest fiber contents',
        imageUrl: 'https://images.unsplash.com/photo-1509458788439-e0990a6ecf9d?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80',
        category: 'High Fiber',
        nutritionalBenefits: ['Very High Fiber', 'Folate', 'Vitamin C', 'Antioxidants'],
        calories: 64,
        isPregnancySafe: true,
        preparation: 'Steam whole artichokes or use hearts in salads',
        ingredients: ['Artichokes', 'Lemon', 'Olive oil'],
      ),
      Meal(
        id: 'fiber_8',
        name: 'Broccoli',
        description: 'Cruciferous vegetable high in fiber and nutrients',
        imageUrl: 'https://images.unsplash.com/photo-1459411621453-7b03977f4bfc?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80',
        category: 'High Fiber',
        nutritionalBenefits: ['High Fiber', 'Vitamin C', 'Folate', 'Vitamin K'],
        calories: 55,
        isPregnancySafe: true,
        preparation: 'Steam lightly to retain nutrients',
        ingredients: ['Fresh broccoli', 'Lemon juice', 'Garlic'],
      ),

      // 6. Iron Rich
      Meal(
        id: 'iron_1',
        name: 'Lean Beef (Well-cooked)',
        description: 'Heme iron for preventing maternal anemia',
        imageUrl: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80',
        category: 'Iron Rich',
        nutritionalBenefits: ['Heme Iron', 'High Protein', 'Zinc', 'B12'],
        calories: 250,
        isPregnancySafe: true,
        preparation: 'Cook to internal temperature of 160°F',
        ingredients: ['Lean beef', 'Onions', 'Bell peppers'],
      ),
      Meal(
        id: 'iron_2',
        name: 'Spinach (Cooked)',
        description: 'Non-heme iron enhanced when cooked',
        imageUrl: 'https://images.unsplash.com/photo-1576045057995-568f588f82fb?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80',
        category: 'Iron Rich',
        nutritionalBenefits: ['Non-heme Iron', 'Folate', 'Vitamin A', 'Vitamin K'],
        calories: 41,
        isPregnancySafe: true,
        preparation: 'Sauté with garlic, pair with vitamin C foods',
        ingredients: ['Fresh spinach', 'Garlic', 'Lemon juice'],
      ),
      Meal(
        id: 'iron_3',
        name: 'Fortified Breakfast Cereal',
        description: 'Iron-fortified cereals for easy iron intake',
        imageUrl: 'https://images.unsplash.com/photo-1574168329407-abbece9e7ba1?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80',
        category: 'Iron Rich',
        nutritionalBenefits: ['Fortified Iron', 'B Vitamins', 'Fiber', 'Folic Acid'],
        calories: 110,
        isPregnancySafe: true,
        preparation: 'Serve with milk and fresh fruit',
        ingredients: ['Fortified cereal', 'Milk', 'Strawberries'],
      ),
      Meal(
        id: 'iron_4',
        name: 'White Beans',
        description: 'Plant-based iron with protein and fiber',
        imageUrl: 'https://images.unsplash.com/photo-1614777986876-75746bcd8b8d?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80',
        category: 'Iron Rich',
        nutritionalBenefits: ['Non-heme Iron', 'Plant Protein', 'Fiber', 'Folate'],
        calories: 249,
        isPregnancySafe: true,
        preparation: 'Use canned (rinsed) or cook from dried',
        ingredients: ['White beans', 'Tomatoes', 'Herbs'],
      ),
      Meal(
        id: 'iron_5',
        name: 'Tofu',
        description: 'Iron-rich plant protein',
        imageUrl: 'https://images.unsplash.com/photo-1609501676725-7186f73b2c92?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80',
        category: 'Iron Rich',
        nutritionalBenefits: ['Non-heme Iron', 'Plant Protein', 'Calcium', 'Isoflavones'],
        calories: 181,
        isPregnancySafe: true,
        preparation: 'Marinate and bake or stir-fry',
        ingredients: ['Firm tofu', 'Soy sauce', 'Ginger'],
      ),
      Meal(
        id: 'iron_6',
        name: 'Blackstrap Molasses',
        description: 'Natural sweetener high in iron',
        imageUrl: 'https://images.unsplash.com/photo-1558961363-fa8fdf82db35?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80',
        category: 'Iron Rich',
        nutritionalBenefits: ['High Iron', 'Calcium', 'Potassium', 'Magnesium'],
        calories: 58,
        isPregnancySafe: true,
        preparation: 'Use sparingly as sweetener in baking or oatmeal',
        ingredients: ['Blackstrap molasses'],
      ),
      Meal(
        id: 'iron_7',
        name: 'Oysters (Ensure fully cooked)',
        description: 'High heme iron content when fully cooked',
        imageUrl: 'https://images.unsplash.com/photo-1617096200347-cb04ae810b1d?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80',
        category: 'Iron Rich',
        nutritionalBenefits: ['Very High Heme Iron', 'Zinc', 'B12', 'Protein'],
        calories: 68,
        isPregnancySafe: true,
        preparation: 'Cook thoroughly to internal temperature of 145°F',
        ingredients: ['Fresh oysters', 'Lemon', 'Herbs'],
      ),
      Meal(
        id: 'iron_8',
        name: 'Pumpkin Seeds',
        description: 'Iron-rich seeds with healthy fats',
        imageUrl: 'https://images.unsplash.com/photo-1571115764595-644a1f56a55c?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80',
        category: 'Iron Rich',
        nutritionalBenefits: ['Non-heme Iron', 'Healthy Fats', 'Zinc', 'Magnesium'],
        calories: 163,
        isPregnancySafe: true,
        preparation: 'Roast lightly or eat raw',
        ingredients: ['Raw pumpkin seeds'],
      ),

      // 7. Calcium Rich
      Meal(
        id: 'calcium_1',
        name: 'Milk (Dairy or Fortified Plant-based)',
        description: 'Primary calcium source for bone health',
        imageUrl: 'https://images.unsplash.com/photo-1550583724-b2692b85b150?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80',
        category: 'Calcium Rich',
        nutritionalBenefits: ['High Calcium', 'Protein', 'Vitamin D', 'Phosphorus'],
        calories: 150,
        isPregnancySafe: true,
        preparation: 'Drink cold or use in smoothies and cereal',
        ingredients: ['Milk', 'Optional: vanilla extract'],
      ),
      Meal(
        id: 'calcium_2',
        name: 'Plain Yogurt',
        description: 'Calcium with probiotics for digestive health',
        imageUrl: 'https://images.unsplash.com/photo-1488477181946-6428a0291777?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80',
        category: 'Calcium Rich',
        nutritionalBenefits: ['High Calcium', 'Probiotics', 'Protein', 'B12'],
        calories: 100,
        isPregnancySafe: true,
        preparation: 'Serve with fresh fruit and honey',
        ingredients: ['Plain yogurt', 'Fresh berries', 'Honey'],
      ),
      Meal(
        id: 'calcium_3',
        name: 'Cheese (Hard, pasteurized varieties)',
        description: 'Concentrated calcium in pasteurized forms',
        imageUrl: 'https://images.unsplash.com/photo-1486297678162-eb2a19b0a32d?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80',
        category: 'Calcium Rich',
        nutritionalBenefits: ['Very High Calcium', 'Protein', 'Vitamin A', 'Phosphorus'],
        calories: 113,
        isPregnancySafe: true,
        preparation: 'Ensure pasteurization, use in moderation',
        ingredients: ['Pasteurized hard cheese'],
      ),
      Meal(
        id: 'calcium_4',
        name: 'Canned Sardines (with bones)',
        description: 'Calcium from edible bones plus omega-3s',
        imageUrl: 'https://images.unsplash.com/photo-1544943911-6e931ad79fc4?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80',
        category: 'Calcium Rich',
        nutritionalBenefits: ['High Calcium', 'Omega-3', 'Protein', 'Vitamin D'],
        calories: 208,
        isPregnancySafe: true,
        preparation: 'Use canned sardines with bones, rinse if desired',
        ingredients: ['Canned sardines', 'Lemon', 'Crackers'],
      ),
      Meal(
        id: 'calcium_5',
        name: 'Tofu (made with calcium sulfate)',
        description: 'Plant-based calcium source',
        imageUrl: 'https://images.unsplash.com/photo-1609501676725-7186f73b2c92?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80',
        category: 'Calcium Rich',
        nutritionalBenefits: ['High Calcium', 'Plant Protein', 'Iron', 'Isoflavones'],
        calories: 181,
        isPregnancySafe: true,
        preparation: 'Check label for calcium sulfate, marinate and cook',
        ingredients: ['Calcium-set tofu', 'Soy sauce', 'Sesame oil'],
      ),
      Meal(
        id: 'calcium_6',
        name: 'Kale',
        description: 'Leafy green high in bioavailable calcium',
        imageUrl: 'https://images.unsplash.com/photo-1515543237350-b3eea1ec8082?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80',
        category: 'Calcium Rich',
        nutritionalBenefits: ['Bioavailable Calcium', 'Vitamin K', 'Vitamin A', 'Folate'],
        calories: 36,
        isPregnancySafe: true,
        preparation: 'Massage raw kale or sauté lightly',
        ingredients: ['Fresh kale', 'Olive oil', 'Lemon juice'],
      ),
      Meal(
        id: 'calcium_7',
        name: 'Calcium-fortified Orange Juice',
        description: 'Vitamin C with added calcium',
        imageUrl: 'https://images.unsplash.com/photo-1600271886742-f049cd451bba?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80',
        category: 'Calcium Rich',
        nutritionalBenefits: ['Fortified Calcium', 'Vitamin C', 'Folate', 'Potassium'],
        calories: 110,
        isPregnancySafe: true,
        preparation: 'Drink fresh, shake well before pouring',
        ingredients: ['Calcium-fortified orange juice'],
      ),
      Meal(
        id: 'calcium_8',
        name: 'Sesame Seeds/Tahini',
        description: 'Calcium-rich seeds and paste',
        imageUrl: 'https://images.unsplash.com/photo-1607272801043-91b3e56e3da1?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80',
        category: 'Calcium Rich',
        nutritionalBenefits: ['High Calcium', 'Healthy Fats', 'Protein', 'Magnesium'],
        calories: 160,
        isPregnancySafe: true,
        preparation: 'Use tahini as spread or add sesame seeds to dishes',
        ingredients: ['Sesame seeds', 'Tahini'],
      ),

      // 8. Folate & Vitamin B12 Rich
      Meal(
        id: 'folate_1',
        name: 'Liver (Limit due to Vitamin A)',
        description: 'Highest folate and B12 source - consult doctor for frequency',
        imageUrl: 'https://images.unsplash.com/photo-1607623814075-e51df1bdc82f?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80',
        category: 'Folate & Vitamin B12 Rich',
        nutritionalBenefits: ['Very High Folate', 'Very High B12', 'Iron', 'Vitamin A'],
        calories: 191,
        isPregnancySafe: true,
        preparation: 'Limit to once weekly due to vitamin A content',
        ingredients: ['Liver (beef or chicken)', 'Onions', 'Herbs'],
      ),
      Meal(
        id: 'folate_2',
        name: 'Eggs (B12)',
        description: 'Complete protein with vitamin B12',
        imageUrl: 'https://images.unsplash.com/photo-1518492104633-130d0cc84637?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80',
        category: 'Folate & Vitamin B12 Rich',
        nutritionalBenefits: ['High B12', 'Complete Protein', 'Choline', 'Vitamin D'],
        calories: 155,
        isPregnancySafe: true,
        preparation: 'Cook thoroughly - avoid raw or undercooked',
        ingredients: ['Eggs', 'Milk', 'Butter'],
      ),
      Meal(
        id: 'folate_3',
        name: 'Beef (Well-cooked, B12)',
        description: 'Heme iron with high B12 content',
        imageUrl: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80',
        category: 'Folate & Vitamin B12 Rich',
        nutritionalBenefits: ['Very High B12', 'Heme Iron', 'Protein', 'Zinc'],
        calories: 250,
        isPregnancySafe: true,
        preparation: 'Cook to safe internal temperature',
        ingredients: ['Lean beef', 'Garlic', 'Herbs'],
      ),
      Meal(
        id: 'folate_4',
        name: 'Fortified Grains/Cereals',
        description: 'Fortified with folate and B12',
        imageUrl: 'https://images.unsplash.com/photo-1574168329407-abbece9e7ba1?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80',
        category: 'Folate & Vitamin B12 Rich',
        nutritionalBenefits: ['Fortified Folate', 'Fortified B12', 'Iron', 'B Vitamins'],
        calories: 110,
        isPregnancySafe: true,
        preparation: 'Check labels for fortification levels',
        ingredients: ['Fortified cereal', 'Milk', 'Berries'],
      ),
      Meal(
        id: 'folate_5',
        name: 'Spinach (Folate)',
        description: 'Leafy green high in natural folate',
        imageUrl: 'https://images.unsplash.com/photo-1576045057995-568f588f82fb?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80',
        category: 'Folate & Vitamin B12 Rich',
        nutritionalBenefits: ['High Folate', 'Iron', 'Vitamin A', 'Vitamin K'],
        calories: 41,
        isPregnancySafe: true,
        preparation: 'Cook lightly to preserve folate',
        ingredients: ['Fresh spinach', 'Garlic', 'Olive oil'],
      ),
      Meal(
        id: 'folate_6',
        name: 'Asparagus (Folate)',
        description: 'Vegetable with high folate content',
        imageUrl: 'https://images.unsplash.com/photo-1459411621453-7b03977f4bfc?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80',
        category: 'Folate & Vitamin B12 Rich',
        nutritionalBenefits: ['Very High Folate', 'Vitamin K', 'Fiber', 'Vitamin A'],
        calories: 27,
        isPregnancySafe: true,
        preparation: 'Steam or roast until tender',
        ingredients: ['Fresh asparagus', 'Lemon', 'Olive oil'],
      ),
      Meal(
        id: 'folate_7',
        name: 'Nutritional Yeast (B12)',
        description: 'Plant-based B12 source for vegetarians',
        imageUrl: 'https://images.unsplash.com/photo-1498837167922-ddd27525d352?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80',
        category: 'Folate & Vitamin B12 Rich',
        nutritionalBenefits: ['Very High B12', 'B Vitamins', 'Protein', 'Fiber'],
        calories: 60,
        isPregnancySafe: true,
        preparation: 'Sprinkle on foods for cheesy flavor',
        ingredients: ['Nutritional yeast'],
      ),
      Meal(
        id: 'folate_8',
        name: 'Black-eyed Peas (Folate)',
        description: 'Legume rich in folate and protein',
        imageUrl: 'https://images.unsplash.com/photo-1498837167922-ddd27525d352?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80',
        category: 'Folate & Vitamin B12 Rich',
        nutritionalBenefits: ['High Folate', 'Plant Protein', 'Fiber', 'Iron'],
        calories: 198,
        isPregnancySafe: true,
        preparation: 'Cook with herbs and vegetables',
        ingredients: ['Black-eyed peas', 'Onion', 'Tomatoes'],
      ),

      // 9. Omega-3 Rich
      Meal(
        id: 'omega3_1',
        name: 'Salmon (Low-mercury choice)',
        description: 'DHA and EPA for fetal brain development',
        imageUrl: 'https://images.unsplash.com/photo-1498837167922-ddd27525d352?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80',
        category: 'Omega-3 Rich',
        nutritionalBenefits: ['High DHA/EPA', 'Protein', 'Vitamin D', 'B Vitamins'],
        calories: 206,
        isPregnancySafe: true,
        preparation: 'Bake, grill, or poach - choose wild-caught when possible',
        ingredients: ['Salmon fillet', 'Lemon', 'Dill'],
      ),
      Meal(
        id: 'omega3_2',
        name: 'Walnuts',
        description: 'Plant-based ALA omega-3 fatty acids',
        imageUrl: 'https://images.unsplash.com/photo-1498837167922-ddd27525d352?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80',
        category: 'Omega-3 Rich',
        nutritionalBenefits: ['ALA Omega-3', 'Healthy Fats', 'Protein', 'Magnesium'],
        calories: 185,
        isPregnancySafe: true,
        preparation: 'Eat raw or add to yogurt, salads',
        ingredients: ['Raw walnuts'],
      ),
      Meal(
        id: 'omega3_3',
        name: 'Chia Seeds',
        description: 'Plant omega-3s with fiber and protein',
        imageUrl: 'https://images.unsplash.com/photo-1498837167922-ddd27525d352?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80',
        category: 'Omega-3 Rich',
        nutritionalBenefits: ['ALA Omega-3', 'Fiber', 'Protein', 'Calcium'],
        calories: 138,
        isPregnancySafe: true,
        preparation: 'Soak to form gel, add to smoothies',
        ingredients: ['Chia seeds', 'Almond milk'],
      ),
      Meal(
        id: 'omega3_4',
        name: 'Flaxseeds',
        description: 'Ground flaxseeds for omega-3 absorption',
        imageUrl: 'https://images.unsplash.com/photo-1498837167922-ddd27525d352?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80',
        category: 'Omega-3 Rich',
        nutritionalBenefits: ['ALA Omega-3', 'Fiber', 'Lignans', 'Protein'],
        calories: 150,
        isPregnancySafe: true,
        preparation: 'Use ground form for better absorption',
        ingredients: ['Ground flaxseeds'],
      ),
      Meal(
        id: 'omega3_5',
        name: 'Edamame',
        description: 'Soy beans with omega-3 and complete protein',
        imageUrl: 'https://images.unsplash.com/photo-1498837167922-ddd27525d352?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80',
        category: 'Omega-3 Rich',
        nutritionalBenefits: ['ALA Omega-3', 'Complete Protein', 'Folate', 'Fiber'],
        calories: 188,
        isPregnancySafe: true,
        preparation: 'Steam and season with sea salt',
        ingredients: ['Edamame pods', 'Sea salt'],
      ),
      Meal(
        id: 'omega3_6',
        name: 'Omega-3 Fortified Eggs',
        description: 'Eggs from hens fed omega-3 rich diet',
        imageUrl: 'https://images.unsplash.com/photo-1498837167922-ddd27525d352?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80',
        category: 'Omega-3 Rich',
        nutritionalBenefits: ['DHA/EPA', 'Complete Protein', 'Choline', 'B12'],
        calories: 155,
        isPregnancySafe: true,
        preparation: 'Cook thoroughly, look for omega-3 fortified labels',
        ingredients: ['Omega-3 eggs', 'Herbs'],
      ),
      Meal(
        id: 'omega3_7',
        name: 'Canned Light Tuna (Limited)',
        description: 'Lower mercury fish with omega-3s - limit intake',
        imageUrl: 'https://images.unsplash.com/photo-1498837167922-ddd27525d352?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80',
        category: 'Omega-3 Rich',
        nutritionalBenefits: ['DHA/EPA', 'Protein', 'Selenium', 'B Vitamins'],
        calories: 179,
        isPregnancySafe: true,
        preparation: 'Limit to 2-3 servings per week, choose light tuna',
        ingredients: ['Canned light tuna', 'Lemon', 'Celery'],
      ),
      Meal(
        id: 'omega3_8',
        name: 'Hemp Seeds',
        description: 'Complete protein with balanced omega fatty acids',
        imageUrl: 'https://images.unsplash.com/photo-1498837167922-ddd27525d352?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80',
        category: 'Omega-3 Rich',
        nutritionalBenefits: ['ALA Omega-3', 'Complete Protein', 'Magnesium', 'Iron'],
        calories: 170,
        isPregnancySafe: true,
        preparation: 'Sprinkle on yogurt, salads, or smoothies',
        ingredients: ['Hemp seeds'],
      ),

      // 10. Hydration Focused
      Meal(
        id: 'hydration_1',
        name: 'Watermelon',
        description: '90% water content for natural hydration',
        imageUrl: 'https://images.unsplash.com/photo-1498837167922-ddd27525d352?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80',
        category: 'Hydration Focused',
        nutritionalBenefits: ['High Water Content', 'Vitamin C', 'Lycopene', 'Potassium'],
        calories: 46,
        isPregnancySafe: true,
        preparation: 'Eat fresh, chilled for refreshing hydration',
        ingredients: ['Fresh watermelon'],
      ),
      Meal(
        id: 'hydration_2',
        name: 'Cucumber',
        description: '95% water with refreshing crunch',
        imageUrl: 'https://images.unsplash.com/photo-1498837167922-ddd27525d352?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80',
        category: 'Hydration Focused',
        nutritionalBenefits: ['Very High Water', 'Low Calories', 'Vitamin K', 'Potassium'],
        calories: 16,
        isPregnancySafe: true,
        preparation: 'Eat raw, add to water for flavor',
        ingredients: ['Fresh cucumber', 'Mint'],
      ),
      Meal(
        id: 'hydration_3',
        name: 'Celery',
        description: 'High water content with natural electrolytes',
        imageUrl: 'https://images.unsplash.com/photo-1498837167922-ddd27525d352?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80',
        category: 'Hydration Focused',
        nutritionalBenefits: ['High Water Content', 'Electrolytes', 'Fiber', 'Vitamin K'],
        calories: 14,
        isPregnancySafe: true,
        preparation: 'Eat raw with nut butter or in salads',
        ingredients: ['Fresh celery', 'Almond butter'],
      ),
      Meal(
        id: 'hydration_4',
        name: 'Strawberries',
        description: '90% water with vitamin C',
        imageUrl: 'https://images.unsplash.com/photo-1498837167922-ddd27525d352?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80',
        category: 'Hydration Focused',
        nutritionalBenefits: ['High Water Content', 'Vitamin C', 'Antioxidants', 'Folate'],
        calories: 49,
        isPregnancySafe: true,
        preparation: 'Wash thoroughly, eat fresh',
        ingredients: ['Fresh strawberries'],
      ),
      Meal(
        id: 'hydration_5',
        name: 'Coconut Water (in moderation)',
        description: 'Natural electrolytes for hydration',
        imageUrl: 'https://images.unsplash.com/photo-1498837167922-ddd27525d352?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80',
        category: 'Hydration Focused',
        nutritionalBenefits: ['Natural Electrolytes', 'Potassium', 'Hydration', 'Low Sugar'],
        calories: 45,
        isPregnancySafe: true,
        preparation: 'Drink fresh or young coconut water in moderation',
        ingredients: ['Pure coconut water'],
      ),
      Meal(
        id: 'hydration_6',
        name: 'Lettuce',
        description: '95% water content in leafy greens',
        imageUrl: 'https://images.unsplash.com/photo-1498837167922-ddd27525d352?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80',
        category: 'Hydration Focused',
        nutritionalBenefits: ['Very High Water', 'Low Calories', 'Folate', 'Vitamin A'],
        calories: 10,
        isPregnancySafe: true,
        preparation: 'Use in salads, wraps, or sandwiches',
        ingredients: ['Fresh lettuce', 'Tomatoes', 'Cucumber'],
      ),
      Meal(
        id: 'hydration_7',
        name: 'Grapefruit',
        description: '88% water with vitamin C boost',
        imageUrl: 'https://images.unsplash.com/photo-1498837167922-ddd27525d352?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80',
        category: 'Hydration Focused',
        nutritionalBenefits: ['High Water Content', 'Vitamin C', 'Fiber', 'Folate'],
        calories: 52,
        isPregnancySafe: true,
        preparation: 'Eat fresh segments, avoid with certain medications',
        ingredients: ['Fresh grapefruit'],
      ),
      Meal(
        id: 'hydration_8',
        name: 'Plain Yogurt',
        description: 'High water content with probiotics',
        imageUrl: 'https://images.unsplash.com/photo-1498837167922-ddd27525d352?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80',
        category: 'Hydration Focused',
        nutritionalBenefits: ['High Water Content', 'Probiotics', 'Protein', 'Calcium'],
        calories: 100,
        isPregnancySafe: true,
        preparation: 'Choose plain varieties, add fresh fruit',
        ingredients: ['Plain yogurt', 'Fresh berries'],
      ),
    ];
  }

  // Default exercises for pregnancy
  List<Exercise> _getDefaultExercises() {
    return [
      Exercise(
        id: 'exercise_1',
        name: 'Walking',
        description: 'Low-impact cardio safe for all trimesters',
        icon: Icons.directions_walk,
        duration: '30 minutes',
        difficulty: 'easy',
        benefits: ['Cardiovascular health', 'Mood improvement', 'Energy boost'],
        isPregnancySafe: true,
        instructions: 'Walk at a comfortable pace for 30 minutes daily',
        trimester: 'all',
      ),
      Exercise(
        id: 'exercise_2',
        name: 'Swimming',
        description: 'Full-body workout with joint support',
        icon: Icons.pool,
        duration: '45 minutes',
        difficulty: 'moderate',
        benefits: ['Full body workout', 'Joint support', 'Reduces swelling'],
        isPregnancySafe: true,
        instructions: 'Swim laps or do water aerobics',
        trimester: 'all',
      ),
      Exercise(
        id: 'exercise_3',
        name: 'Prenatal Yoga',
        description: 'Flexibility and relaxation for pregnancy',
        icon: Icons.self_improvement,
        duration: '60 minutes',
        difficulty: 'easy',
        benefits: ['Flexibility', 'Relaxation', 'Better sleep', 'Pain relief'],
        isPregnancySafe: true,
        instructions: 'Follow prenatal yoga routines',
        trimester: 'all',
      ),
      Exercise(
        id: 'exercise_4',
        name: 'Light Weights',
        description: 'Strength training with light weights',
        icon: Icons.fitness_center,
        duration: '20 minutes',
        difficulty: 'moderate',
        benefits: ['Muscle strength', 'Bone health', 'Posture improvement'],
        isPregnancySafe: true,
        instructions: 'Use light weights with proper form',
        trimester: 'first,second',
      ),
      Exercise(
        id: 'exercise_5',
        name: 'Stationary Bike',
        description: 'Safe cardio with lower back support',
        icon: Icons.directions_bike,
        duration: '25 minutes',
        difficulty: 'moderate',
        benefits: ['Cardio fitness', 'Leg strength', 'Low impact'],
        isPregnancySafe: true,
        instructions: 'Cycle at moderate intensity',
        trimester: 'first,second',
      ),
      Exercise(
        id: 'exercise_6',
        name: 'Stretching',
        description: 'Gentle stretches for flexibility',
        icon: Icons.spa,
        duration: '15 minutes',
        difficulty: 'easy',
        benefits: ['Flexibility', 'Muscle relaxation', 'Stress relief'],
        isPregnancySafe: true,
        instructions: 'Gentle stretching routine',
        trimester: 'all',
      ),
    ];
  }

  // Get recommended meals for today (ONLY doctor-prescribed meals)
  Future<List<Meal>> getTodaysMeals() async {
    try {
      final userId = await SessionManager.getUserId();
      print('NutritionService: Getting meals for user ID: $userId');
      
      if (userId != null) {
        // Try to get doctor-recommended meals
        final doctorRecommendations = await _backendService.getDoctorRecommendations(userId);
        print('NutritionService: Doctor recommendations: $doctorRecommendations');
        
        if (doctorRecommendations != null && doctorRecommendations['meals'] != null) {
          final List<dynamic> mealData = doctorRecommendations['meals'];
          print('NutritionService: Found ${mealData.length} prescribed meals');
          final meals = mealData.map((meal) => Meal.fromJson(meal)).toList();
          print('NutritionService: Parsed meals: ${meals.map((m) => m.name).toList()}');
          return meals;
        } else {
          print('NutritionService: No meals found in doctor recommendations');
        }
      } else {
        print('NutritionService: No user ID found');
      }
    } catch (e) {
      print('NutritionService: Error getting doctor recommendations: $e');
    }
    
    // Return empty list if no doctor recommendations
    print('NutritionService: Returning empty meals list');
    return [];
  }

  // Get recommended exercises for today (either from doctor or default)
  Future<List<Exercise>> getTodaysExercises() async {
    try {
      final userId = await SessionManager.getUserId();
      if (userId != null) {
        // Try to get doctor-recommended exercises
        final doctorRecommendations = await _backendService.getDoctorRecommendations(userId);
        
        if (doctorRecommendations != null && doctorRecommendations['exercises'] != null) {
          final List<dynamic> exerciseData = doctorRecommendations['exercises'];
          print('NutritionService: Found ${exerciseData.length} prescribed exercises');
          final exercises = exerciseData.map((exercise) => Exercise.fromJson(exercise)).toList();
          print('NutritionService: Parsed exercises: ${exercises.map((e) => e.name).toList()}');
          return exercises;
        } else {
          print('NutritionService: No exercises found in doctor recommendations');
        }
      }
    } catch (e) {
      print('NutritionService: Error getting doctor recommendations: $e');
    }
    
    // Return empty list if no doctor recommendations
    print('NutritionService: Returning empty exercises list');
    return [];
  }

  // Get all available meals by category
  Future<Map<String, List<Meal>>> getAllMealsByCategory() async {
    final meals = _getDefaultMeals();
    final Map<String, List<Meal>> categorizedMeals = {};
    
    for (final meal in meals) {
      if (!categorizedMeals.containsKey(meal.category)) {
        categorizedMeals[meal.category] = [];
      }
      categorizedMeals[meal.category]!.add(meal);
    }
    
    return categorizedMeals;
  }

  // Get all available exercises
  Future<List<Exercise>> getAllExercises() async {
    return _getDefaultExercises();
  }

  // Get meals by category for doctor prescription
  Future<List<Meal>> getMealsByCategory(String category) async {
    final allMeals = _getDefaultMeals();
    print('NutritionService: Searching for category: "$category"');
    print('NutritionService: Total meals available: ${allMeals.length}');
    
    final filteredMeals = allMeals.where((meal) => meal.category == category).toList();
    print('NutritionService: Found ${filteredMeals.length} meals for category "$category"');
    
    if (filteredMeals.isEmpty) {
      final availableCategories = allMeals.map((meal) => meal.category).toSet().toList();
      print('NutritionService: Available categories: $availableCategories');
    }
    
    return filteredMeals;
  }
}
