// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJihIjnpRv9fwQKl3PLx-la1yTb24oQ5g',
    appId: '1:503679307705:web:f8e3fa319544838e897068',
    messagingSenderId: '503679307705',
    projectId: 'safemother-flutterapp',
    authDomain: 'safemother-flutterapp.firebaseapp.com',
    storageBucket: 'safemother-flutterapp.firebasestorage.app',
    measurementId: 'G-MPTXZ6ME4J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFCTdIYQ6DkF5cmlbeQkqNFArqxQzlobk',
    appId: '1:503679307705:android:bf0886aa9782ddb7897068',
    messagingSenderId: '503679307705',
    projectId: 'safemother-flutterapp',
    storageBucket: 'safemother-flutterapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKSehNrnXiNWQnFHJH50CkXasnFNebgUU',
    appId: '1:503679307705:ios:b7019c10ee6fea9d897068',
    messagingSenderId: '503679307705',
    projectId: 'safemother-flutterapp',
    storageBucket: 'safemother-flutterapp.firebasestorage.app',
    iosBundleId: 'com.example.safemothermobapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKSehNrnXiNWQnFHJH50CkXasnFNebgUU',
    appId: '1:503679307705:ios:b7019c10ee6fea9d897068',
    messagingSenderId: '503679307705',
    projectId: 'safemother-flutterapp',
    storageBucket: 'safemother-flutterapp.firebasestorage.app',
    iosBundleId: 'com.example.safemothermobapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJihIjnpRv9fwQKl3PLx-la1yTb24oQ5g',
    appId: '1:503679307705:web:5b8ca89ff262c54f897068',
    messagingSenderId: '503679307705',
    projectId: 'safemother-flutterapp',
    authDomain: 'safemother-flutterapp.firebaseapp.com',
    storageBucket: 'safemother-flutterapp.firebasestorage.app',
    measurementId: 'G-LMHY70X8RP',
  );
}
