// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUEIFeFgFDp2JJtmUrYGJlIFo_UF8q55Q',
    appId: '1:757432772551:web:1ed823fa28618c96a89be2',
    messagingSenderId: '757432772551',
    projectId: 'safemother-e0e40',
    authDomain: 'safemother-e0e40.firebaseapp.com',
    storageBucket: 'safemother-e0e40.firebasestorage.app',
    measurementId: 'G-TSXNS1R3C5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8h1hoI-dgK1FLyeWh_jUrSO-F8tRRBrE',
    appId: '1:757432772551:android:06716c47c0f7b625a89be2',
    messagingSenderId: '757432772551',
    projectId: 'safemother-e0e40',
    storageBucket: 'safemother-e0e40.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWdRr_s5Xd8M-WZ0ljE5a-_PVYRBuIxps',
    appId: '1:757432772551:ios:dd8a8966bccb20a7a89be2',
    messagingSenderId: '757432772551',
    projectId: 'safemother-e0e40',
    storageBucket: 'safemother-e0e40.firebasestorage.app',
    iosBundleId: 'com.example.safemothermobapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWdRr_s5Xd8M-WZ0ljE5a-_PVYRBuIxps',
    appId: '1:757432772551:ios:dd8a8966bccb20a7a89be2',
    messagingSenderId: '757432772551',
    projectId: 'safemother-e0e40',
    storageBucket: 'safemother-e0e40.firebasestorage.app',
    iosBundleId: 'com.example.safemothermobapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDUEIFeFgFDp2JJtmUrYGJlIFo_UF8q55Q',
    appId: '1:757432772551:web:b9dab548c6fdd0cca89be2',
    messagingSenderId: '757432772551',
    projectId: 'safemother-e0e40',
    authDomain: 'safemother-e0e40.firebaseapp.com',
    storageBucket: 'safemother-e0e40.firebasestorage.app',
    measurementId: 'G-KC05NTVB1C',
  );
}
